//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        //public Task()
        //{
        //    this.ParentTasks = new HashSet<ParentTask>();
        //}
    
        public int Task_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string Task1 { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> IsTaskEnded { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        public string ParentTask { get; set; }
        
        public virtual ICollection<ParentTask> ParentTasks { get; set; }
    }
}
